app_composition:
    resource: "@AppBundle/Resources/config/routing/composition.yml"
    prefix:   /composition

_show:
  pattern: /app/network/{id}
  defaults: { _controller: AppBundle:Default:show }