scan_history:
    path:     /
    defaults: { _controller: "AppBundle:ScanHistory:index" }

scan_history_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ScanHistory:show" }

scan_history_new:
    path:     /new
    defaults: { _controller: "AppBundle:ScanHistory:new" }

scan_history_create:
    path:     /create
    defaults: { _controller: "AppBundle:ScanHistory:create" }
    methods:  POST

scan_history_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ScanHistory:edit" }

scan_history_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:ScanHistory:update" }
    methods:  [POST, PUT]

scan_history_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ScanHistory:delete" }
    methods:  [POST, DELETE]
