services:
  app.composition_controller:
    class: AppBundle\Controller\CompositionController
    arguments: [ @doctrine.orm.entity_manager, @app.composition_history_controller, @app.hash_generator, @app.serializer ]

  app.composition_history_controller:
    class: AppBundle\Controller\CompositionHistoryController
    arguments: [ @doctrine.orm.entity_manager ]

  app.xsd_validator:
    class: AppBundle\Util\XsdValidator

  app.hash_generator:
    class: AppBundle\Util\HashGenerator

  app.serializer:
    class: AppBundle\Util\Serializer
    arguments: [ @jms_serializer ]