services:
  app.composition_controller:
    class: AppBundle\Service\CompositionService
    arguments: [ @doctrine.orm.entity_manager, @app.composition_history, @app.composition_cache, @app.hash_generator, @app.serializer ]

  app.composition_history:
    class: AppBundle\Service\CompositionHistoryService
    arguments: [ @doctrine.orm.entity_manager ]

  app.composition_cache:
    class: AppBundle\Service\CompositionCacheService
    arguments: [ @doctrine.orm.entity_manager ]

  app.xsd_validator:
    class: AppBundle\Service\Util\XsdValidator

  app.hash_generator:
    class: AppBundle\Service\Util\HashGenerator

  app.component_diff:
    class: AppBundle\Service\Util\ComponentDiff

  app.serializer:
    class: AppBundle\Service\Util\Serializer
    arguments: [ @jms_serializer ]

  app.collector:
    class: AppBundle\Service\Util\Collector

  app.doctrine_listener:
    class: AppBundle\EventListener\UniqueComponent
    tags:
      - { name: doctrine.event_listener, event: prePersist }